### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'accessToken')

### ISSUE THREAD

**Issue by ShaanWocker** [ShaanWocker/Admin-Dashboard#2]
Module../src/requestMethods.js
src/requestMethods.js:4...

  1 | import axios from "axios";
  2 | 
  3 | const BASE_URL = "http://localhost:5000/api/";
=>  4 | const TOKEN = JSON.parse(JSON.parse(localStorage.getItem("persist:root")).user).currentUser.accessToken;
  5 | 
  6 | export const publicRequest = axios.create({
  7 |     baseURL: BASE_URL,

**Comment by rainiersvn** [comment]
Ima need some more context around this. In what file is this snippet located?

**Comment by ShaanWocker** [comment]
https://us04web.zoom.us/j/5731470830?pwd=ZXlBTDA2NjhXRDh5RUNCZjZDQlViUT09

**Comment by ShaanWocker** [comment]
I have found the issue in store.js, I was calling dispatch incoreectly. 

I have also added a temporary fix for the localStorage in requestMethods.
